Added workflow test scripts

diff --git a/.github/workflows/tune_kernels.yml b/.github/workflows/tune_kernels.yml
--- a/.github/workflows/tune_kernels.yml
+++ b/.github/workflows/tune_kernels.yml
@@ -3,13 +3,9 @@ name: Tune Wave Kernels
 on:
   workflow_dispatch:
     inputs:
-      config_url:
-        description: "URL to tuning configuration"
-        required: false
-      config_json:
-        description: "Stringified JSON for tuning configuration"
-        required: false
-        default: "[]"
+      problems_url:
+        description: "URL to problems to tune"
+        required: true
       num_trials:
         description: "Number of trials per kernel for tuning"
         required: false
@@ -37,11 +33,7 @@ jobs:
 
   tuning:
     name: Tune Kernels
-    runs-on: linux-mi325-8gpu-ossci-nod-ai
-
-    env:
-      CONFIG_JSON: ${{ inputs.config_json }}
-      WAVE_CACHE_ON: 0
+    runs-on: ubuntu-latest
 
     concurrency:
       group: benchmarking
@@ -56,11 +48,6 @@ jobs:
         with:
           python-version: "3.12"
 
-      - name: "Setting up Rust"
-        uses: actions-rust-lang/setup-rust-toolchain@v1
-        with:
-          toolchain: stable
-
       - name: Setup venv
         run: |
           python3 -m venv tune_venv
@@ -71,32 +58,19 @@ jobs:
           pip install -r requirements.txt
           pip install wave-lang
 
-      - name: Install Triton
-        run: |
-          source tune_venv/bin/activate
-          git clone --recursive https://github.com/ROCm/aiter.git
-          cd aiter
-          python setup.py develop
-
       - name: Load Tuning Configuration from URL
-        if: ${{ inputs.config_url }}
         run: |
-          curl -o tune_config.json ${{ inputs.config_url }}
-
-      - name: Load Tuning Configuration from JSON string
-        if: ${{ !inputs.config_url }}
-        run: |
-          echo "$CONFIG_JSON" > tune_config.json
+          curl -o problems.json ${{ inputs.problems_url }}
 
       - name: Validate Configuration File
         run: |
           source tune_venv/bin/activate
-          python -m json.tool tune_config.json > /dev/null || { echo "Error: Invalid JSON format"; exit 1; }
+          python -m json.tool problems.json > /dev/null || { echo "Error: Invalid JSON format"; exit 1; }
 
       - name: Tune
         run: |
           source tune_venv/bin/activate
-          python -m kernel_bench.cli.bench --tune --load_problems=tune_config.json --backend=${{ inputs.backend }} --num_trials=${{ inputs.num_trials }} --machine=mi325x
+          python -m workflow_tests.mock_tuning --load_problems=problems.json --backend=${{ inputs.backend }} --num_trials=${{ inputs.num_trials }} --machine=mi325x
 
       - name: Upload tuning results
         uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
