fixed venv setup

diff --git a/.github/workflows/tune_kernels.yml b/.github/workflows/tune_kernels.yml
--- a/.github/workflows/tune_kernels.yml
+++ b/.github/workflows/tune_kernels.yml
@@ -53,11 +53,6 @@ jobs:
         run: |
           echo "$CONFIG_JSON" > tune_config.json
 
-      - name: Validate Configuration File
-        run: |
-          source tune_venv/bin/activate
-          python -m json.tool tune_config.json > /dev/null || { echo "Error: Invalid JSON format"; exit 1; }
-
       - name: Setup venv
         run: |
           python3 -m venv tune_venv
@@ -67,6 +62,11 @@ jobs:
           pip install -r pytorch-rocm-requirements.txt
           pip install -r requirements.txt
           pip install wave-lang
+
+      - name: Validate Configuration File
+        run: |
+          source tune_venv/bin/activate
+          python -m json.tool tune_config.json > /dev/null || { echo "Error: Invalid JSON format"; exit 1; }
 
       - name: Tune Attention
         run: |
